<?php
/**
 * [JishiGou] (C)2005 - 2099 Cenwor Inc.
 *
 * This is NOT a freeware, use is subject to license terms
 *
 * @Filename modules.php $
 *
 * @Author http://www.jishigou.net $
 *
 * @Date 2013 773660383 2478 $
 */



$config['modules'] = array (
  'account' => 1,
  'album' => 1,
  'ajax' => 1,
  'api' => 1,
  'app' => 1,
  'async' => 1,
  'attach' => 1,
  'backup' => 1,
  'baidu' => 1,
  'blacklist' => 1,
  'block' => 1,
  'cache' => 1,
  'channel' => 1,
  'city' => 1,
  'class' => 1,
  'cms' => 1,
  'company' => 1,
  'data' => 1,
  'db' => 1,
  'dedecms' => 1,
  'default' => 1,
  'delete' => 1,
  'department' => 1,
  'dig' => 1,
  'dzbbs' => 1,
  'error_log' => 1,
  'log' => 1,
  'event' => 1,
  'face' => 1,
  'fenlei' => 1,
  'fjau' => 1,
  'friend' => 1,
  'get_password' => 1,
  'guest' => 1,
  'images' => 1,
  'imjiqiren' => 1,
  'include' => 1,
  'income' => 1,
  'index' => 1,
  'install' => 1,
  'item' => 1,
  'kaixin' => 1,
  'link' => 1,
  'live' => 1,
  'log' => 1,
  'logic' => 1,
  'login' => 1,
  'logs' => 1,
  'longtext' => 1,
  'master' => 1,
  'medal' => 1,
  'media' => 1,
  'member' => 1,
  'memcache' => 1,
  'misc' => 1,
  'mobile' => 1,
  'modify' => 1,
  'module' => 1,
  'modules' => 1,
  'more' => 1,
  'nedu' => 1,
  'notice' => 1,
  'oauth2' => 1,
  'other' => 1,
  'output' => 1,
  'passport' => 1,
  'patch' => 1,
  'people' => 1,
  'phpwind' => 1,
  'plugin' => 1,
  'plugindesign' => 1,
  'pm' => 1,
  'profile' => 1,
  'program' => 1,
  'public' => 1,
  'qmd' => 1,
  'qqwb' => 1,
  'qun' => 1,
  'recdtopic' => 1,
  'remark' => 1,
  'reminded' => 1,
  'renren' => 1,
  'report' => 1,
  'reward' => 1,
  'rewrite' => 1,
  'robot' => 1,
  'role' => 1,
  'role_action' => 1,
  'role_module' => 1,
  'rss' => 1,
  'schedule' => 1,
  'search' => 1,
  'sessions' => 1,
  'setting' => 1,
  'settings' => 1,
  'share' => 1,
  'show' => 1,
  'sign' => 1,
  'skin' => 1,
  'sms' => 1,
  'square' => 1,
  'tag' => 1,
  'talk' => 1,
  'task' => 1,
  'templates' => 1,
  'test' => 1,
  'theme' => 1,
  'tools' => 1,
  'topic' => 1,
  'topic_manage' => 1,
  'uc_client' => 1,
  'ucenter' => 1,
  'update' => 1,
  'upgrade' => 1,
  'upload' => 1,
  'uploadattach' => 1,
  'uploadify' => 1,
  'url' => 1,
  'user' => 1,
  'user_tag' => 1,
  'validate' => 1,
  'verify' => 1,
  'view' => 1,
  'vipintro' => 1,
  'vote' => 1,
  'wall' => 1,
  'wap' => 1,
  'weather' => 1,
  'web_info' => 1,
  'wqueue' => 1,
  'www' => 1,
  'xwb' => 1,
  'yy' => 1,
  'ldap' => 1,
  'hzswb' => 1,
  'sinopec' => 1,
  'wechat' => 1,
  'navigation'=>1,
  'qun_announcement' => 1,
  'failedlogins' => 1,
  'contest'=>1,
  'feature'=>1,
  'job'=>1,
  'feed'=>1,
  'help'=>1,
);
?>