<?php
/**
 * [JishiGou] (C)2005 - 2099 Cenwor Inc.
 *
 * This is NOT a freeware, use is subject to license terms
 *
 * @Filename settings.default.php $
 *
 * @Author http://www.jishigou.net $
 *
 * @Date 2014 687758186 7677 $
 */

 $config = array (
  'acceleration_mode' => '0',
  'account_on_off' => 1,
  'ad_enable' => 0,
  'add_topic_need_face' => '0',
  'ajax_topic_time' => '60',
  'allowed_visit_role_list' => '2,7,3,5,108,109,110,111,112,113,114,115,116,117',
  'android_download_url' => '',
  'anonymous_enable' => '1',
  'api_enable' => 0,
  'attach_enable' => 1,
  'attach_file_type' => 'zip|rar|txt|doc|xls|pdf|ppt|docx|xlsx|pptx',
  'attach_files_limit' => 5,
  'attach_size_limit' => 5120,
  'auth_key' => 'kJU9WdHk8m1PXuDK58tB4KwFC12kLfDE',
  'cache_db_to_memory' => 1,
  'cache_file_to_memory' => 1,
  'cache_table_num' => 16,
  'card_pic_enable' =>
  array (
    'is_card_pic' => 1,
  ),
  'channel_enable' => 1,
  'channel_must' => 0,
  'channel_recommend' => '1',
  'channel_rtitle' => '网站公告',
  'charset' => 'utf-8',
  'city_status' => '1',
  'clear_format_open' => '1',
  'close_second_verify_enable' => '0',
  'company_enable' => '0',
  'contest_available' => '1',
  'cookie_domain' => '',
  'cookie_expire' => '30',
  'cookie_path' => '/',
  'cookie_prefix' => 'JishiGou_Lq6CyF_',
  'copyright' => '',
  'count_online_user' => '1',
  'credits_filed' => 'extcredits2',
  'db_host' => '192.168.1.121',
  'db_name' => 'jishigou4',
  'db_pass' => 'jishigou4',
  'db_port' => '',
  'db_table_prefix' => 'jishigou_',
  'db_type' => 'mysql',
  'db_user' => 'jishigou4',
  'default_code' => 'only_login',
  'default_company' => '',
  'default_department' => '',
  'default_job' => '',
  'default_module' => 'topic',
  'department_enable' => '0',
  'edit_face_enable' => '1',
  'edit_nickname_enable' => '0',
  'email_must_be_true' => '0',
  'event_open' => '1',
  'extcredits_enable' => 1,
  'extra_domain' => '',
  'extra_domains' =>
  array (
  ),
  'face_enable' => 1,
  'face_verify' => '0',
  'feed_type' =>
  array (
    0 => 'post',
    1 => 'forward',
    2 => 'dig',
    3 => 'favorite',
  ),
  'feed_user' =>
  array (
    1 => 'admin',
  ),
  'first_topic_to_channel' => '5',
  'follow_limit' => 2000,
  'gzip' => 0,
  'hot_tag_recommend_enable' => 1,
  'hzswb_enable' => 0,
  'icp' => '备案申请中',
  'image_enable' => 1,
  'image_size' => 2048,
  'image_size_limit' => 2097152,
  'image_thumb_quality' => '75',
  'image_uploadify_queue_size_limit' => '3',
  'image_width_p' => '280',
  'index_meta_description' => '',
  'index_meta_keywords' => '',
  
  'invite_by_admin' => '1',
  'invite_count_max' => '30',
  'invite_limit' => '5',
  'iphone_download_url' => '',
  'iphone_passphrase' => '',
  'iphone_pem_file' => '',
  'iphone_push_enable' => 0,
  'is_qmd' => 0,
  'is_signature' => '1',
  'is_topic_user_follow' => '1',
  'jishigou_founder' => '1',
  'jsg_member_login_extract' => '',
  'last_archive_member_uid' => NULL,
  'last_archive_topic_relation_tid' => 400,
  'last_archive_topic_tid' => 0,
  'lastpost_time' => '5',
  'level_radio' => '1',
  'login_by_uid' => '0',
  'maxthumbheight' => '6000',
  'maxthumbwidth' => '800',
  'memory' =>
  array (
    'memcache' =>
    array (
      'enable' => 1,
      'connect' =>
      array (
        0 =>
        array (
          'server' => '127.0.0.1',
          'port' => '11211',
        ),
      ),
    ),
  ),
  'memory_enable' => 0,
  'meta_description' => '',
  'meta_keywords' => '',
  'mobile_url' => 'http://dev.jishigou.net/mobile',
  'music_enable' => 1,
  'nickname_length' => 0,
  'no_record_guest' => 0,
  'no_verify_email_role_id' => '5',
  'normal_default_role_id' => '3',
  'notice_to_admin' => '',
  'notice_to_new_user' => '',
  'notice_to_new_user_news' => '',
  'notice_to_validatesucssee_user' => '',
  'notice_to_waitvalidate_user' => '',
  'on_publish_notice' => '有什么新鲜事与大家分享？',
  'only_show_vip_topic' => '0',
  'page_title' => '',
  'qmd_file_url' => './images/qmd/',
  'qmd_fonts_url' => '',
  'qmd_link_display' => 1,
  'qqwb_enable' => 1,
  'qun_attach_enable' => 1,
  'qun_setting' =>
  array (
    'qun_open' => '1',
  ),
  'reg_email_forbid' => '',
  'reg_email_verify' => '0',
  'reg_step3_radio' => '1',
  'reg_step4_radio' => '1',
  'reg_step5_radio' => '1',
  'reg_step6_radio' => '0',
  'reg_step7_radio' => '1',
  'regclosemessage' => '',
  'register_check_ip_enable' => 1,
  'register_invite_input' => '1',
  'register_invite_input2' => '0',
  'register_link_display' => '1',
  'regiter_tuijian' =>
  array (
    0 => 'channel',
    1 => 'dig',
    2 => 'recd',
  ),
  'regstatus' =>
  array (
    0 => 'normal',
    1 => 'invite',
  ),
  'reply_mode_normal' => 0,
  'reward_open' => 1,
  'rewrite_enable' => 0,
  'robot_enable' => 0,
  'safe_key' => 'EHz4GAu0gx54JdgmeLEySkPcXBaNI1Jt',
  'same_city' => '1',
  'seccode_comment' => 1,
  'seccode_enable' => 1,
  'seccode_forward' => 1,
  'seccode_login' => 1,
  'seccode_logins' => '1',
  'seccode_no_email' => 0,
  'seccode_no_photo' => 1,
  'seccode_no_vip' => 0,
  'seccode_password' => 1,
  'seccode_passwords' => '1',
  'seccode_pri_key' => 'ba654d1411c3ba4e3ed6b8b2ef29a470',
  'seccode_pub_key' => '98583a76eb813b39381fdb1684908dc0',
  'seccode_publish' => 1,
  'seccode_purview' => '3,4,5,108',
  'seccode_purviews' =>
  array (
    3 => 3,
    4 => 4,
    5 => 5,
    108 => 108,
  ),
  'seccode_register' => 1,
  'seccode_registers' => '1',
  'seccode_sms' => 1,
  'sendmailday' => '0',
  'sign' =>
  array (
    'sign_enable' => '1',
  ),
  'sign_tag' =>
  array (
    'enable' => 1,
  ),
  'sign_verify' => '0',
  'sina_enable' => 1,
  'site_admin_email' => 'foxis@qq.com',
  'site_admin_nickname' => '管理员',
  'site_closed' => '0',
  'site_domain' => 'dev.jishigou.net',
  'site_name' => '记事狗',
  'site_notice' => NULL,
  'site_url' => 'http://dev.jishigou.net',
  'slide_enable' => 0,
  'slide_index_enable' => 1,
  'sms_enable' => 0,
  'sms_extra_enable' => 1,
  'sms_link_display' => 0,
  'style_three_tol' => 1,
  'tag_enable' => 1,
  'template_path' => 'default',
  'template_root_path' => './templates/',
  'theme_bg_color' => '#edece9',
  'theme_bg_image_type' => 'center',
  'theme_id' => 't1',
  'theme_link_color' => '#4d97ef',
  'theme_text_color' => '#333',
  'third_party_regstatus' =>
  array (
    0 => 'sina',
    1 => 'qqwb',
  ),
  'thumb_cut_type' => '0',
  'thumbheight' => 120,
  'thumbwidth' => 120,
  'timezone' => '8',
  'tongji' => '<div style="display:none"><script language="javascript" type="text/javascript" src="http://js.users.51.la/439714.js"></script><noscript><a href="http://www.51.la/?439714" target="_blank"><img alt="" src="http://img.users.51.la/439714.asp" style="border:none" /></a></noscript></div>',
  'topic_cut_length' => 140,
  'topic_home_page' => '',
  'topic_input_length' => 1000,
  'topic_length' => 140,
  'topic_level_radio' => '1',
  'topic_modify_time' => '60',
  'topic_myhome_time_limit' => '60',
  'topic_view_share_code' => '',
  'topic_vip' => '0',
  'total_page_default' => '100',
  'ucenter_enable' => 0,
  'upgrade_lock_time' => NULL,
  'upgrade_to_lock_version' => 46,
  'verify' => '0',
  'verify_alert' => '1',
  'vest_enable' => 1,
  'vest_role' => '2,7,109,110,111,112,113,114,115,116,117',
  'video_enable' => 1,
  'video_status' => '1',
  'visitIp' => '',
  'visitMember' => '',
  'visitState' => '0',
  'vote_open' => '1',
  'vote_verify' => '0',
  'vote_vip' => '0',
  'wap' => '1',
  'wap_reg_radio' => '0',
  'wap_url' => 'http://dev.jishigou.net/wap',
  'watermark_contents' =>
  array (
    0 => 'url',
  ),
  'watermark_contents_color' => '#ffffff',
  'watermark_contents_size' => '12',
  'watermark_enable' => '1',
  'watermark_position' => 4,
  'website_home_page' => 'normal',
  'wechat_enable' => '0',
  'wechat_qrcode' => './images/jishigou_qr_code.jpg',
  'widget_enable' => '0',
  'word_type_enable' => '1',
); ?>